[package]
name = "coinbase-pro-rs"
version = "0.1.0"
authors = ["oliver.hines <oliver.hines@btinternet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
